/**
 * Storefront catalog — transcribed from the printed Ahmed El-Deriny price list.
 *
 * This is the single source of truth for categories, products and selling
 * prices. After editing run `npm run catalog:build` (regenerates
 * prisma/catalog-export.json + prisma/firestore-export.json) then `npm run db:seed`.
 *
 * priceUnit: "sqm" = price per square meter, "meter" = price per running meter,
 * "piece" = flat price per piece.
 */

export const CATEGORIES = [
  {
    categoryId: "Outdoor",
    slug: "outdoor",
    nameAr: "اليفط الأوت دور",
    nameEn: "Outdoor Signage",
    priceUnit: "sqm",
    pricingType: "per_sqm",
    groups: [
      { id: "banner", nameAr: "البانر", nameEn: "Banner" },
      { id: "vinyl", nameAr: "الفينيل", nameEn: "Vinyl" },
      { id: "flex", nameAr: "الفليكس", nameEn: "Flex" },
      { id: "finishing", nameAr: "التشطيب والتقطيع", nameEn: "Finishing & Cutting" },
    ],
    products: [
      {
        id: "banner-380g",
        nameAr: "بانر 380 جرام",
        nameEn: "Banner 380g",
        price: 65,
        groupId: "banner",
        featured: true,
        descriptionAr: "بانر خارجي 380 جرام — الاختيار الاقتصادي للافتات المحلات والإعلانات المؤقتة.",
        descriptionEn: "380g outdoor banner — the economical choice for shop signage and short-term ads.",
      },
      {
        id: "banner-440g",
        nameAr: "بانر 440 جرام",
        nameEn: "Banner 440g",
        price: 110,
        groupId: "banner",
        descriptionAr: "بانر ثقيل 440 جرام يتحمل الشمس والرياح لفترات أطول.",
        descriptionEn: "Heavy 440g banner that stands up to sun and wind for longer.",
      },
      {
        id: "see-through",
        nameAr: "سي ثرو",
        nameEn: "See-Through",
        price: 130,
        groupId: "vinyl",
        descriptionAr: "خامة سي ثرو للواجهات الزجاجية — إعلان واضح من الخارج ورؤية من الداخل.",
        descriptionEn: "See-through media for glass façades — visible advertising outside, clear view inside.",
      },
      {
        id: "flex",
        nameAr: "فليكس",
        nameEn: "Flex",
        price: 120,
        groupId: "flex",
        descriptionAr: "فليكس عالي الجودة للافتات الكبيرة والواجهات المضيئة.",
        descriptionEn: "High-quality flex for large signage and lit façades.",
      },
      {
        id: "reflective-banner",
        nameAr: "بانر عاكس",
        nameEn: "Reflective Banner",
        price: 350,
        groupId: "banner",
        featured: true,
        descriptionAr: "بانر عاكس للضوء — مثالي للطرق واللافتات الليلية.",
        descriptionEn: "Light-reflective banner — ideal for roadside and night-time signage.",
      },
      {
        id: "coated-banner",
        nameAr: "بانر كوتيد",
        nameEn: "Coated Banner",
        price: 230,
        groupId: "banner",
        descriptionAr: "بانر كوتيد بطبقة حماية تحافظ على الألوان لفترة أطول.",
        descriptionEn: "Coated banner with a protective layer that keeps colors vivid for longer.",
      },
      {
        id: "white-vinyl",
        nameAr: "فينيل أبيض",
        nameEn: "White Vinyl",
        price: 95,
        groupId: "vinyl",
        descriptionAr: "فينيل أبيض لاصق للطباعة على الأسطح المستوية والواجهات.",
        descriptionEn: "White adhesive vinyl for printing on flat surfaces and façades.",
      },
      {
        id: "coated-flex",
        nameAr: "فليكس كوتيد",
        nameEn: "Coated Flex",
        price: 220,
        groupId: "flex",
        descriptionAr: "فليكس كوتيد بخامة أسمك وطباعة أنقى للاستخدام الخارجي الطويل.",
        descriptionEn: "Coated flex — thicker media and sharper print for long outdoor use.",
      },
      {
        id: "transparent-vinyl",
        nameAr: "فينيل شفاف",
        nameEn: "Transparent Vinyl",
        price: 110,
        groupId: "vinyl",
        descriptionAr: "فينيل شفاف للزجاج والفتارين مع الحفاظ على دخول الضوء.",
        descriptionEn: "Transparent vinyl for glass and display windows while letting light through.",
      },
      {
        id: "printed-reflective-vinyl",
        nameAr: "فينيل عاكس مطبوع",
        nameEn: "Printed Reflective Vinyl",
        price: 450,
        groupId: "vinyl",
        descriptionAr: "فينيل عاكس مطبوع لعلامات المرور والسيارات واللافتات الليلية.",
        descriptionEn: "Printed reflective vinyl for traffic signs, vehicles and night-time signage.",
      },
      {
        id: "printed-frosted-vinyl",
        nameAr: "فينيل مصنفر مطبوع",
        nameEn: "Printed Frosted Vinyl",
        price: 280,
        groupId: "vinyl",
        descriptionAr: "فينيل مصنفر مطبوع يعطي خصوصية أنيقة للزجاج والمكاتب.",
        descriptionEn: "Printed frosted vinyl that adds elegant privacy to glass and offices.",
      },
      {
        id: "cellophane",
        nameAr: "سلفان مط أو لامع",
        nameEn: "Matte or Gloss Cellophane",
        price: 70,
        groupId: "finishing",
        descriptionAr: "طبقة سلفان مط أو لامع لحماية المطبوع وإطالة عمره.",
        descriptionEn: "Matte or gloss cellophane layer that protects the print and extends its life.",
      },
      {
        id: "plotter-cutting",
        nameAr: "تقطيع فقط كاتر بلوتر",
        nameEn: "Plotter Cutting Only",
        price: 130,
        groupId: "finishing",
        descriptionAr: "خدمة تقطيع كاتر بلوتر للحروف والأشكال بدون طباعة.",
        descriptionEn: "Cutter-plotter service for letters and shapes without printing.",
      },
    ],
  },

  {
    categoryId: "Indoor",
    slug: "indoor",
    nameAr: "اليفط الإن دور",
    nameEn: "Indoor Signage",
    priceUnit: "sqm",
    pricingType: "per_sqm",
    groups: [
      { id: "banner", nameAr: "البانر", nameEn: "Banner" },
      { id: "vinyl", nameAr: "الفينيل", nameEn: "Vinyl" },
      { id: "premium", nameAr: "خامات مميزة", nameEn: "Premium Media" },
    ],
    products: [
      {
        id: "banner-380g",
        nameAr: "بانر 380 جرام",
        nameEn: "Banner 380g",
        price: 135,
        groupId: "banner",
        descriptionAr: "بانر إندور 380 جرام بطباعة نظيفة للمعارض والقاعات.",
        descriptionEn: "380g indoor banner with clean print for exhibitions and halls.",
      },
      {
        id: "banner-440g",
        nameAr: "بانر 440 جرام",
        nameEn: "Banner 440g",
        price: 160,
        groupId: "banner",
        descriptionAr: "بانر إندور 440 جرام أسمك وأثبت للاستخدام المتكرر.",
        descriptionEn: "Thicker, sturdier 440g indoor banner for repeated use.",
      },
      {
        id: "glossy",
        nameAr: "جلوسي",
        nameEn: "Glossy",
        price: 280,
        groupId: "premium",
        featured: true,
        descriptionAr: "ورق جلوسي بألوان زاهية ودقة عالية للبوسترات والصور.",
        descriptionEn: "Glossy paper with vivid colors and high detail for posters and photos.",
      },
      {
        id: "white-vinyl",
        nameAr: "فينيل أبيض",
        nameEn: "White Vinyl",
        price: 180,
        groupId: "vinyl",
        descriptionAr: "فينيل أبيض لاصق للحوائط والديكورات الداخلية.",
        descriptionEn: "White adhesive vinyl for interior walls and décor.",
      },
      {
        id: "transparent-vinyl",
        nameAr: "فينيل شفاف",
        nameEn: "Transparent Vinyl",
        price: 165,
        groupId: "vinyl",
        descriptionAr: "فينيل شفاف للفواصل الزجاجية والواجهات الداخلية.",
        descriptionEn: "Transparent vinyl for glass partitions and interior fronts.",
      },
      {
        id: "canvas",
        nameAr: "كانفس",
        nameEn: "Canvas",
        price: 290,
        groupId: "premium",
        descriptionAr: "طباعة كانفس بملمس القماش الفني — مثالية للوحات والديكور.",
        descriptionEn: "Canvas printing with an artistic fabric texture — ideal for wall art and décor.",
      },
      {
        id: "backlight",
        nameAr: "باك لايت",
        nameEn: "Backlight",
        price: 355,
        groupId: "premium",
        featured: true,
        descriptionAr: "خامة باك لايت للصناديق المضيئة — ألوان تتوهج مع الإضاءة الخلفية.",
        descriptionEn: "Backlight media for light boxes — colors that glow with backlighting.",
      },
    ],
  },

  {
    categoryId: "Stands",
    slug: "stands",
    nameAr: "الأستندات",
    nameEn: "Stands",
    priceUnit: "piece",
    pricingType: "stands",
    groups: [
      { id: "roll-up", nameAr: "الرول أب", nameEn: "Roll-Up" },
      { id: "adjust-banner", nameAr: "أدجاست بانر", nameEn: "Adjustable Banner" },
      { id: "x-banner", nameAr: "أكس بانر", nameEn: "X-Banner" },
    ],
    products: [
      {
        id: "roll-up-80-banner",
        nameAr: "رول أب عرض 80 سم — بانر",
        nameEn: "Roll-Up 80 cm — Banner",
        price: 750,
        groupId: "roll-up",
        descriptionAr: "ستاند رول أب عرض 80 سم بطباعة على خامة البانر، سهل الفك والتركيب.",
        descriptionEn: "80 cm roll-up stand printed on banner media, quick to set up and pack away.",
      },
      {
        id: "roll-up-80-glossy",
        nameAr: "رول أب عرض 80 سم — جلوسي",
        nameEn: "Roll-Up 80 cm — Glossy",
        price: 1150,
        groupId: "roll-up",
        descriptionAr: "ستاند رول أب عرض 80 سم بطباعة جلوسي عالية الوضوح.",
        descriptionEn: "80 cm roll-up stand with high-definition glossy print.",
      },
      {
        id: "roll-up-85-banner",
        nameAr: "رول أب عرض 85 سم — بانر",
        nameEn: "Roll-Up 85 cm — Banner",
        price: 850,
        groupId: "roll-up",
        descriptionAr: "ستاند رول أب عرض 85 سم بطباعة على خامة البانر.",
        descriptionEn: "85 cm roll-up stand printed on banner media.",
      },
      {
        id: "roll-up-85-glossy",
        nameAr: "رول أب عرض 85 سم — جلوسي",
        nameEn: "Roll-Up 85 cm — Glossy",
        price: 1230,
        groupId: "roll-up",
        descriptionAr: "ستاند رول أب عرض 85 سم بطباعة جلوسي عالية الوضوح.",
        descriptionEn: "85 cm roll-up stand with high-definition glossy print.",
      },
      {
        id: "roll-up-100-banner",
        nameAr: "رول أب عرض 100 سم — بانر",
        nameEn: "Roll-Up 100 cm — Banner",
        price: 1050,
        groupId: "roll-up",
        featured: true,
        descriptionAr: "ستاند رول أب عرض 100 سم — المقاس الأكثر طلباً للمعارض والمؤتمرات.",
        descriptionEn: "100 cm roll-up stand — the most requested size for exhibitions and conferences.",
      },
      {
        id: "roll-up-100-glossy",
        nameAr: "رول أب عرض 100 سم — جلوسي",
        nameEn: "Roll-Up 100 cm — Glossy",
        price: 1350,
        groupId: "roll-up",
        descriptionAr: "ستاند رول أب عرض 100 سم بطباعة جلوسي عالية الوضوح.",
        descriptionEn: "100 cm roll-up stand with high-definition glossy print.",
      },
      {
        id: "roll-up-120-banner",
        nameAr: "رول أب عرض 120 سم — بانر",
        nameEn: "Roll-Up 120 cm — Banner",
        price: 1350,
        groupId: "roll-up",
        descriptionAr: "ستاند رول أب عرض 120 سم لمساحة عرض أكبر.",
        descriptionEn: "120 cm roll-up stand for a wider display area.",
      },
      {
        id: "roll-up-120-glossy",
        nameAr: "رول أب عرض 120 سم — جلوسي",
        nameEn: "Roll-Up 120 cm — Glossy",
        price: 1700,
        groupId: "roll-up",
        descriptionAr: "ستاند رول أب عرض 120 سم بطباعة جلوسي عالية الوضوح.",
        descriptionEn: "120 cm roll-up stand with high-definition glossy print.",
      },
      {
        id: "adjust-banner-240",
        nameAr: "أدجاست بانر 240 × 240",
        nameEn: "Adjustable Banner 240 × 240",
        price: 6900,
        groupId: "adjust-banner",
        widthCm: 240,
        heightCm: 240,
        descriptionAr: "ستاند أدجاست بانر 240 × 240 سم بارتفاع وعرض قابلين للضبط — خلفية مثالية للمؤتمرات.",
        descriptionEn: "240 × 240 cm adjustable banner stand with variable height and width — a perfect conference backdrop.",
      },
      {
        id: "x-banner-60-160",
        nameAr: "أكس بانر 60 × 160 سم",
        nameEn: "X-Banner 60 × 160 cm",
        price: 800,
        groupId: "x-banner",
        widthCm: 60,
        heightCm: 160,
        descriptionAr: "ستاند أكس بانر 60 × 160 سم خفيف الوزن وسهل النقل.",
        descriptionEn: "60 × 160 cm X-banner stand — lightweight and easy to carry.",
      },
      {
        id: "x-banner-80-180",
        nameAr: "أكس بانر 80 × 180 سم",
        nameEn: "X-Banner 80 × 180 cm",
        price: 900,
        groupId: "x-banner",
        widthCm: 80,
        heightCm: 180,
        descriptionAr: "ستاند أكس بانر 80 × 180 سم لمساحة عرض أكبر بنفس سهولة التركيب.",
        descriptionEn: "80 × 180 cm X-banner stand — a larger display with the same easy setup.",
      },
    ],
  },

  {
    categoryId: "PopUp",
    slug: "pop-up",
    nameAr: "البوب أب",
    nameEn: "Pop-Up Displays",
    priceUnit: "piece",
    pricingType: "per_unit",
    priceNoteAr: "السعر شامل الطباعة",
    priceNoteEn: "Price includes printing",
    groups: [
      { id: "pop-up-wall", nameAr: "حوائط البوب أب", nameEn: "Pop-Up Walls" },
      { id: "pop-up-extras", nameAr: "كاونتر وطاولات", nameEn: "Counters & Tables" },
    ],
    products: [
      {
        id: "straight-2x3",
        nameAr: "بوب أب استريت 2 × 3",
        nameEn: "Pop-Up Straight 2 × 3",
        price: 10500,
        groupId: "pop-up-wall",
        descriptionAr: "حائط بوب أب استريت 2 × 3 شامل الطباعة — خلفية مستقيمة للمعارض.",
        descriptionEn: "2 × 3 straight pop-up wall including printing — a flat exhibition backdrop.",
      },
      {
        id: "curve-2x3",
        nameAr: "بوب أب كيرف 2 × 3",
        nameEn: "Pop-Up Curve 2 × 3",
        price: 10700,
        groupId: "pop-up-wall",
        descriptionAr: "حائط بوب أب كيرف 2 × 3 شامل الطباعة — انحناءة تعطي عمق للجناح.",
        descriptionEn: "2 × 3 curved pop-up wall including printing — a curve that adds depth to your booth.",
      },
      {
        id: "straight-3x3",
        nameAr: "بوب أب استريت 3 × 3",
        nameEn: "Pop-Up Straight 3 × 3",
        price: 10900,
        groupId: "pop-up-wall",
        featured: true,
        descriptionAr: "حائط بوب أب استريت 3 × 3 شامل الطباعة — المقاس الأكثر استخداماً في المعارض.",
        descriptionEn: "3 × 3 straight pop-up wall including printing — the most used exhibition size.",
      },
      {
        id: "curve-3x3",
        nameAr: "بوب أب كيرف 3 × 3",
        nameEn: "Pop-Up Curve 3 × 3",
        price: 11200,
        groupId: "pop-up-wall",
        descriptionAr: "حائط بوب أب كيرف 3 × 3 شامل الطباعة.",
        descriptionEn: "3 × 3 curved pop-up wall including printing.",
      },
      {
        id: "straight-3x4",
        nameAr: "بوب أب استريت 3 × 4",
        nameEn: "Pop-Up Straight 3 × 4",
        price: 12200,
        groupId: "pop-up-wall",
        descriptionAr: "حائط بوب أب استريت 3 × 4 شامل الطباعة لمساحة عرض أوسع.",
        descriptionEn: "3 × 4 straight pop-up wall including printing for a wider display.",
      },
      {
        id: "curve-3x4",
        nameAr: "بوب أب كيرف 3 × 4",
        nameEn: "Pop-Up Curve 3 × 4",
        price: 12400,
        groupId: "pop-up-wall",
        descriptionAr: "حائط بوب أب كيرف 3 × 4 شامل الطباعة.",
        descriptionEn: "3 × 4 curved pop-up wall including printing.",
      },
      {
        id: "straight-3x5",
        nameAr: "بوب أب استريت 3 × 5",
        nameEn: "Pop-Up Straight 3 × 5",
        price: 13200,
        groupId: "pop-up-wall",
        descriptionAr: "حائط بوب أب استريت 3 × 5 شامل الطباعة — أكبر مساحة عرض في المجموعة.",
        descriptionEn: "3 × 5 straight pop-up wall including printing — the largest display in the range.",
      },
      {
        id: "curve-3x5",
        nameAr: "بوب أب كيرف 3 × 5",
        nameEn: "Pop-Up Curve 3 × 5",
        price: 13400,
        groupId: "pop-up-wall",
        descriptionAr: "حائط بوب أب كيرف 3 × 5 شامل الطباعة.",
        descriptionEn: "3 × 5 curved pop-up wall including printing.",
      },
      {
        id: "counter",
        nameAr: "بوب أب كاونتر",
        nameEn: "Pop-Up Counter",
        price: 7200,
        groupId: "pop-up-extras",
        descriptionAr: "كاونتر بوب أب شامل الطباعة — مكتب استقبال متنقل لجناح المعرض.",
        descriptionEn: "Pop-up counter including printing — a portable reception desk for your booth.",
      },
      {
        id: "promotion-table",
        nameAr: "برموشن تيبل",
        nameEn: "Promotion Table",
        price: 5800,
        groupId: "pop-up-extras",
        descriptionAr: "طاولة ترويجية شاملة الطباعة — خفيفة وسريعة التركيب للأنشطة الميدانية.",
        descriptionEn: "Promotional table including printing — light and fast to assemble for field activations.",
      },
    ],
  },

  {
    categoryId: "DTF",
    slug: "dtf",
    nameAr: "طباعة DTF و UV DTF",
    nameEn: "DTF & UV DTF Printing",
    priceUnit: "meter",
    pricingType: "per_unit",
    groups: [
      { id: "dtf", nameAr: "طباعة DTF", nameEn: "DTF Printing" },
      { id: "uv-dtf", nameAr: "طباعة UV DTF", nameEn: "UV DTF Printing" },
    ],
    products: [
      {
        id: "4-pass",
        nameAr: "DTF 4 باص والتطريز",
        nameEn: "DTF 4 Pass & Embroidery",
        price: 110,
        groupId: "dtf",
        widthCm: 58,
        heightCm: 100,
        descriptionAr: "طباعة DTF 4 باص للتيشرتات والتطريز — المتر مقاس 58 × 100 سم.",
        descriptionEn: "DTF 4-pass printing for apparel and embroidery — one meter measures 58 × 100 cm.",
      },
      {
        id: "6-pass",
        nameAr: "DTF 6 باص والتطريز",
        nameEn: "DTF 6 Pass & Embroidery",
        price: 130,
        groupId: "dtf",
        widthCm: 58,
        heightCm: 100,
        featured: true,
        descriptionAr: "طباعة DTF 6 باص بكثافة ألوان أعلى وثبات أفضل — المتر مقاس 58 × 100 سم.",
        descriptionEn: "DTF 6-pass printing with denser color and better durability — one meter measures 58 × 100 cm.",
      },
      {
        id: "uv-1-layer",
        nameAr: "UV DTF طبقة واحدة",
        nameEn: "UV DTF Single Layer",
        price: 360,
        groupId: "uv-dtf",
        widthCm: 58,
        heightCm: 90,
        descriptionAr: "UV DTF طبقة واحدة بنص بارز خفيف — يفضل عمل عينة أولاً لأنه لا يناسب كل المنتجات. المتر مقاس 58 × 90 سم.",
        descriptionEn: "Single-layer UV DTF with a light raised finish — a sample is recommended as it does not suit every product. One meter measures 58 × 90 cm.",
      },
      {
        id: "uv-2-layers",
        nameAr: "UV DTF طبقتين",
        nameEn: "UV DTF Double Layer",
        price: 500,
        groupId: "uv-dtf",
        widthCm: 58,
        heightCm: 90,
        featured: true,
        descriptionAr: "UV DTF طبقتين بنص أكثر بروزاً — يتم على 98% من المنتجات والخامات. المتر مقاس 58 × 90 سم.",
        descriptionEn: "Double-layer UV DTF with a more raised finish — works on 98% of products and materials. One meter measures 58 × 90 cm.",
      },
      {
        id: "uv-3-layers",
        nameAr: "UV DTF ثلاث طبقات",
        nameEn: "UV DTF Triple Layer",
        price: 800,
        groupId: "uv-dtf",
        widthCm: 58,
        heightCm: 90,
        descriptionAr: "UV DTF ثلاث طبقات بأعلى درجة بروز — يتم على 98% من المنتجات والخامات. المتر مقاس 58 × 90 سم.",
        descriptionEn: "Triple-layer UV DTF with the highest raised finish — works on 98% of products and materials. One meter measures 58 × 90 cm.",
      },
      {
        id: "uv-gold",
        nameAr: "UV DTF Gold",
        nameEn: "UV DTF Gold",
        price: 750,
        groupId: "uv-dtf",
        widthCm: 58,
        heightCm: 90,
        descriptionAr: "UV DTF جولد بلمسة ذهبية فاخرة للهدايا والعلامات المميزة. المتر مقاس 58 × 90 سم.",
        descriptionEn: "Gold UV DTF with a premium metallic finish for gifts and standout branding. One meter measures 58 × 90 cm.",
      },
    ],
  },
  {
    categoryId: "DeskSets",
    slug: "desk-sets",
    nameAr: "طقم المكتب محفور الاسم",
    nameEn: "Engraved Desk Sets",
    priceUnit: "piece",
    pricingType: "per_unit",
    groups: [
      { id: "leather", nameAr: "أطقم جلد مجزع", nameEn: "Grained Leather Sets" },
    ],
    products: [
      {
        id: "black-grained",
        nameAr: "طقم مكتب جلد مجزع أسود",
        nameEn: "Black Grained Leather Desk Set",
        price: 1050,
        groupId: "leather",
        featured: true,
        image: "/images/products/desk-set-black.jpg",
        descriptionAr: "طقم مكتب جلد مجزع أسود فاخر مع إمكانية حفر الاسم على الباغة — يشمل مفرش المكتب وحامل الأقلام ومنظم الأوراق وقاعدة الباغة.",
        descriptionEn: "Premium black grained leather desk set with optional name engraving on the plate — includes desk pad, pen holder, document organizer, and nameplate base.",
      },
      {
        id: "brown-grained",
        nameAr: "طقم مكتب جلد مجزع بنى محروق",
        nameEn: "Burnt Brown Grained Leather Desk Set",
        price: 1050,
        groupId: "leather",
        featured: true,
        image: "/images/products/desk-set-brown.jpg",
        descriptionAr: "طقم مكتب جلد مجزع بنى محروق أنيق مع إمكانية حفر الاسم على الباغة — تشكيلة مكتملة للمكتب التنفيذي.",
        descriptionEn: "Elegant burnt-brown grained leather desk set with optional name engraving — a complete executive desk collection.",
      },
    ],
  },
  {
    categoryId: "WoodDeskSets",
    slug: "wood-desk-sets",
    nameAr: "طقم المكتب خشب الزان",
    nameEn: "Beech Wood Desk Sets",
    priceUnit: "piece",
    pricingType: "per_unit",
    priceNoteAr: "يُباع جاهزًا كما هو — بدون حفر اسم",
    priceNoteEn: "Sold ready as shown — no name engraving",
    groups: [
      { id: "beech", nameAr: "خشب الزان", nameEn: "Beech Wood" },
    ],
    products: [
      {
        id: "dark-brown",
        nameAr: "طقم مكتب خشب بنى غامق",
        nameEn: "Dark Brown Wood Desk Set",
        price: 3200,
        groupId: "beech",
        featured: true,
        image: "/images/products/wood-desk-dark-brown.jpg",
        descriptionAr: "طقم مكتب خشب زان بنى غامق جاهز للبيع كما هو — يشمل صينية أوراق دورين وحامل أقلام وساعة ومفرش المكتب. بدون حفر اسم.",
        descriptionEn: "Ready-to-sell dark brown beech wood desk set — includes two-tier tray, pen holder, clock, and desk pad. No name engraving.",
      },
      {
        id: "espresso",
        nameAr: "طقم مكتب خشب بنى داكن",
        nameEn: "Espresso Dark Wood Desk Set",
        price: 3200,
        groupId: "beech",
        featured: true,
        image: "/images/products/wood-desk-espresso.jpg",
        descriptionAr: "طقم مكتب خشب زان بنى داكن بتشطيب فاخر — تشكيلة مكتملة تُباع جاهزة بدون حفر اسم.",
        descriptionEn: "Premium espresso-dark beech wood desk set — a complete ready-made collection sold without name engraving.",
      },
      {
        id: "leather-brown",
        nameAr: "طقم مكتب خشب جلد بنى",
        nameEn: "Brown Leather-Wood Desk Set",
        price: 3200,
        groupId: "beech",
        featured: true,
        image: "/images/products/wood-desk-leather-brown.jpg",
        descriptionAr: "طقم مكتب خشب زان مع لمسة جلد بنى — جاهز للبيع كما هو بدون حفر اسم على الباغة.",
        descriptionEn: "Beech wood desk set with brown leather accents — sold ready as shown, without name engraving.",
      },
    ],
  },
  {
    categoryId: "DeskBases",
    slug: "desk-bases",
    nameAr: "قاعدات المكتب",
    nameEn: "Desk Bases",
    priceUnit: "piece",
    pricingType: "per_unit",
    priceNoteAr: "تنفع حفر أبيض أو طباعة ألوان",
    priceNoteEn: "White engraving or full-color printing",
    groups: [
      { id: "crystal", nameAr: "قواعد كريستال", nameEn: "Crystal Bases" },
    ],
    products: [
      {
        id: "crystal-color",
        nameAr: "قاعدة مكتب كريستال — طباعة ألوان أو حفر أبيض",
        nameEn: "Crystal Desk Base — Color Print or White Engraving",
        price: 350,
        groupId: "crystal",
        featured: true,
        image: "/images/products/crystal-desk-bases.jpg",
        descriptionAr: "قاعدة مكتب كريستال بعدة أشكال — السعر يشمل الطباعة بالألوان أو الحفر بالأبيض وعلبة قطيفة. اختَر الشكل المناسب لك.",
        descriptionEn: "Crystal desk base in multiple shapes — price includes color printing or white engraving plus a velvet box. Choose your preferred shape.",
      },
      {
        id: "crystal-gold-imported",
        nameAr: "قاعدة كريستال مستورد ذهبى",
        nameEn: "Imported Gold Crystal Desk Base",
        price: 1850,
        groupId: "crystal",
        featured: true,
        image: "/images/products/crystal-base-gold.jpg",
        descriptionAr: "قاعدة كريستال مستورد ذهبى فاخرة مع حاملَي أقلام — تنفع عليها الطباعة بالألوان أو الحفر بالأبيض.",
        descriptionEn: "Premium imported gold crystal desk base with dual pen holders — suitable for color printing or white engraving.",
      },
    ],
  },
  {
    categoryId: "AppreciationCertificates",
    slug: "appreciation-certificates",
    nameAr: "شهادات التقدير",
    nameEn: "Appreciation Certificates",
    priceUnit: "piece",
    pricingType: "per_unit",
    priceNoteAr: "السعر شامل الكافر والشهادة",
    priceNoteEn: "Price includes cover and certificate",
    groups: [
      { id: "covers", nameAr: "كافر بالشهادة", nameEn: "Cover with Certificate" },
    ],
    products: [
      {
        id: "ribbon",
        nameAr: "كافر فيونكة بالشهادة",
        nameEn: "Ribbon Bow Cover with Certificate",
        price: 130,
        groupId: "covers",
        featured: true,
        image: "/images/products/cert-cover-ribbon.jpg",
        descriptionAr: "كافر شهادة تقدير بفيونكة أنيقة ولوحة شكر وتقدير ذهبية — شامل الشهادة.",
        descriptionEn: "Appreciation certificate cover with an elegant ribbon bow and gold plaque — certificate included.",
      },
      {
        id: "wood",
        nameAr: "كافر خشب بالشهادة",
        nameEn: "Wooden Cover with Certificate",
        price: 130,
        groupId: "covers",
        featured: true,
        image: "/images/products/cert-cover-wood.jpg",
        descriptionAr: "كافر خشب محفور بنقوش دقيقة ولوحة شكر وتقدير — شامل الشهادة.",
        descriptionEn: "Laser-cut wooden certificate cover with an appreciation plaque — certificate included.",
      },
      {
        id: "grad-cap",
        nameAr: "كافر كاب تخرج بالشهادة",
        nameEn: "Graduation Cap Cover with Certificate",
        price: 130,
        groupId: "covers",
        featured: true,
        image: "/images/products/cert-cover-grad-cap.jpg",
        descriptionAr: "كافر أسود بزخارف ذهبية وكاب تخرج — مثالي لحفلات التخرج، شامل الشهادة.",
        descriptionEn: "Black cover with gold accents and a graduation-cap motif — ideal for graduations, certificate included.",
      },
      {
        id: "stamp",
        nameAr: "كافر بالبصمة بالشهادة",
        nameEn: "Embossed Stamp Cover with Certificate",
        price: 130,
        groupId: "covers",
        featured: true,
        image: "/images/products/cert-cover-stamp.jpg",
        descriptionAr: "كافر أحمر ببصمة ذهبية ولوحة شكر وتقدير — شامل الشهادة.",
        descriptionEn: "Red embossed cover with a gold stamp plaque — certificate included.",
      },
      {
        id: "frame",
        nameAr: "كافر برواز بصمة بالشهادة",
        nameEn: "Framed Stamp Cover with Certificate",
        price: 130,
        groupId: "covers",
        featured: true,
        image: "/images/products/cert-cover-frame.jpg",
        descriptionAr: "كافر كحلي ببرواز بصمة ذهبي فخم — شامل الشهادة.",
        descriptionEn: "Navy cover with a luxurious gold stamped frame — certificate included.",
      },
      {
        id: "tassel",
        nameAr: "كافر شريطة بالشهادة",
        nameEn: "Tassel Cover with Certificate",
        price: 130,
        groupId: "covers",
        featured: true,
        image: "/images/products/cert-cover-tassel.jpg",
        descriptionAr: "كافر بلونين مع شريطة ذهبية ولوحة شكر وتقدير — شامل الشهادة.",
        descriptionEn: "Two-tone cover with a gold tassel and appreciation plaque — certificate included.",
      },
    ],
  },
  {
    categoryId: "Nameplates",
    slug: "nameplates",
    nameAr: "باغة محفور عليها الاسم",
    nameEn: "Engraved Nameplates",
    priceUnit: "piece",
    pricingType: "per_unit",
    priceNoteAr: "السعر حسب المقاس والنص — تواصل معنا",
    priceNoteEn: "Price depends on size and text — contact us",
    groups: [
      { id: "metal", nameAr: "باغة معدنية", nameEn: "Metal Nameplates" },
    ],
    products: [
      {
        id: "gold",
        nameAr: "باغة ذهبى محفور عليها الاسم حفر أسود",
        nameEn: "Gold Nameplate — Black Engraving",
        price: 0,
        groupId: "metal",
        featured: true,
        image: "/images/products/nameplate-gold.jpg",
        descriptionAr: "باغة ذهبى فاخرة محفور عليها الاسم بحفر أسود واضح — مثالية للمكاتب والهدايا التنفيذية. السعر حسب المقاس والنص.",
        descriptionEn: "Premium gold nameplate with crisp black engraved name — ideal for desks and executive gifts. Price depends on size and text.",
      },
      {
        id: "silver",
        nameAr: "باغة فضى محفور عليها الاسم حفر أسود",
        nameEn: "Silver Nameplate — Black Engraving",
        price: 0,
        groupId: "metal",
        featured: true,
        image: "/images/products/nameplate-silver.jpg",
        descriptionAr: "باغة فضى أنيقة محفور عليها الاسم بحفر أسود واضح — لمسة رسمية راقية للمكتب. السعر حسب المقاس والنص.",
        descriptionEn: "Elegant silver nameplate with crisp black engraved name — a refined formal desk accent. Price depends on size and text.",
      },
    ],
  },
];
